import Link from 'next/link'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { Image, FolderOpen, Sparkles, Settings, Mail, Download, Plus, ArrowRight, CheckCircle, Clock, Star, TrendingUp, Eye, Heart, MessageSquare, Award, Calendar, FileText, Users, Search, Share2, Printer, ChevronDown } from 'lucide-react'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { supabaseAdmin } from '@/utils/supabase'
import { CertificatesTourButton } from './CertificatesTourButton'

async function getCertificateStats() {
  try {
    // Get total certificates generated
    const { count: totalCertificates } = await supabaseAdmin
      .from('certificates')
      .select('*', { count: 'exact', head: true })

    // Get total templates (active ones)
    const { count: totalTemplates } = await supabaseAdmin
      .from('certificate_templates')
      .select('*', { count: 'exact', head: true })

    // Get events with certificates
    const { count: eventsWithCertificates } = await supabaseAdmin
      .from('certificates')
      .select('event_id', { count: 'exact', head: true })

    return {
      totalCertificates: totalCertificates || 0,
      totalTemplates: totalTemplates || 0,
      eventsWithCertificates: eventsWithCertificates || 0
    }
  } catch (error) {
    console.error('Error fetching certificate stats:', error)
    return {
      totalCertificates: 0,
      totalTemplates: 0,
      eventsWithCertificates: 0
    }
  }
}

async function getRecentActivity(userId: string) {
  try {
    // Get recent certificates generated by the user
    const { data: recentCertificates } = await supabaseAdmin
      .from('certificates')
      .select(`
        id,
        generated_at,
        event_id,
        events!inner(title)
      `)
      .eq('generated_by', userId)
      .order('generated_at', { ascending: false })
      .limit(3)

    // Get recent templates created by the user
    const { data: recentTemplates } = await supabaseAdmin
      .from('certificate_templates')
      .select('id, name, created_at')
      .eq('created_by', userId)
      .order('created_at', { ascending: false })
      .limit(3)

    return {
      recentCertificates: recentCertificates || [],
      recentTemplates: recentTemplates || []
    }
  } catch (error) {
    console.error('Error fetching recent activity:', error)
    return {
      recentCertificates: [],
      recentTemplates: []
    }
  }
}

async function getSharedTemplates(userId: string) {
  try {
    // Get templates shared by others (not created by current user)
    const { data: sharedTemplates } = await supabaseAdmin
      .from('certificate_templates')
      .select(`
        id,
        name,
        created_at,
        shared_at,
        created_by,
        users!certificate_templates_created_by_fkey(name)
      `)
      .eq('is_shared', true)
      .neq('created_by', userId)
      .order('shared_at', { ascending: false })
      .limit(6)

    return sharedTemplates || []
  } catch (error) {
    console.error('Error fetching shared templates:', error)
    return []
  }
}

async function getFeaturedTemplates() {
  try {
    // Get most popular templates (most used certificates)
    const { data: featuredTemplates } = await supabaseAdmin
      .from('certificate_templates')
      .select(`
        id,
        name,
        created_at,
        is_shared,
        users!certificate_templates_created_by_fkey(name)
      `)
      .eq('is_shared', true)
      .order('created_at', { ascending: false })
      .limit(3)

    return featuredTemplates || []
  } catch (error) {
    console.error('Error fetching featured templates:', error)
    return []
  }
}

export default async function CertificatesPage() {
  const session = await getServerSession(authOptions)
  const stats = await getCertificateStats()
  const activity = await getRecentActivity(session?.user?.id || '')
  const sharedTemplates = await getSharedTemplates(session?.user?.id || '')
  const featuredTemplates = await getFeaturedTemplates()
  return (
    <div className="space-y-6">
        {/* Header */}
        <div className="mb-8">
          <div className="flex items-start justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Certificate System</h1>
            <p className="text-gray-600">Create professional certificates for your event attendees</p>
            </div>
            <CertificatesTourButton />
          </div>
        </div>

        {/* Quick Actions Bar */}
        <div className="mb-8">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <Link href="/certificates/select-event" className="block" data-tour="certificates-create-new">
              <Card className="border-2 border-green-200 bg-gradient-to-br from-green-50 to-emerald-50 hover:shadow-lg hover:scale-[1.02] transition-all duration-300 cursor-pointer h-32">
                <CardContent className="p-4 h-full flex items-center">
                  <div className="flex items-center gap-3 w-full">
                    <div className="w-8 h-8 bg-green-500 rounded flex items-center justify-center flex-shrink-0">
                      <Plus className="h-4 w-4 text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="font-semibold text-gray-900 text-base leading-tight">Create New</h3>
                      <p className="text-sm text-gray-600 leading-tight">Start from scratch</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Link>

            <Link href="/certificates/generate" className="block" data-tour="certificates-generate-now">
              <Card className="border-2 border-blue-200 bg-gradient-to-br from-blue-50 to-indigo-50 hover:shadow-lg hover:scale-[1.02] transition-all duration-300 cursor-pointer h-32">
                <CardContent className="p-4 h-full flex items-center">
                  <div className="flex items-center gap-3 w-full">
                    <div className="w-8 h-8 bg-blue-500 rounded flex items-center justify-center flex-shrink-0">
                      <Sparkles className="h-4 w-4 text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="font-semibold text-gray-900 text-base leading-tight">Generate Now</h3>
                      <p className="text-sm text-gray-600 leading-tight">Use existing template</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Link>

            <Link href="/certificates/templates" className="block" data-tour="certificates-template-library">
              <Card className="border-2 border-purple-200 bg-gradient-to-br from-purple-50 to-pink-50 hover:shadow-lg hover:scale-[1.02] transition-all duration-300 cursor-pointer h-32">
                <CardContent className="p-4 h-full flex items-center">
                  <div className="flex items-center gap-3 w-full">
                    <div className="w-8 h-8 bg-purple-500 rounded flex items-center justify-center flex-shrink-0">
                      <FolderOpen className="h-4 w-4 text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="font-semibold text-gray-900 text-base leading-tight">Template Library</h3>
                      <p className="text-sm text-gray-600 leading-tight">Browse and manage templates</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Link>

            {/* Certificate Manager */}
            <Link href="/certificates/manage" className="block" data-tour="certificates-manager">
              <Card className="border-2 border-orange-200 bg-gradient-to-br from-orange-50 to-amber-50 hover:shadow-lg hover:scale-[1.02] transition-all duration-300 cursor-pointer h-32">
                <CardContent className="p-4 h-full flex items-center">
                  <div className="flex items-center gap-3 w-full">
                    <div className="w-8 h-8 bg-orange-500 rounded flex items-center justify-center flex-shrink-0">
                      <Settings className="h-4 w-4 text-white" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <h3 className="font-semibold text-gray-900 text-base leading-tight">Certificate Manager</h3>
                      <p className="text-sm text-gray-600 leading-tight">View and manage certificates</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </Link>
          </div>
        </div>

        {/* Recent Activity & Stats Section */}
        <div className="mb-12">
          <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
            {/* Recent Activity */}
            <Card className="lg:col-span-2" data-tour="certificates-recent-activity">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <TrendingUp className="h-5 w-5 text-blue-600" />
                  Recent Activity
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  {activity.recentCertificates.length > 0 ? (
                    activity.recentCertificates.map((cert, index) => (
                      <div key={cert.id} className="flex items-center gap-3 p-3 bg-green-50 rounded-lg border border-green-200">
                        <div className="w-8 h-8 bg-green-500 rounded-full flex items-center justify-center">
                          <Award className="h-4 w-4 text-white" />
                        </div>
                        <div className="flex-1">
                          <p className="text-sm font-medium text-gray-900">Certificates generated for "{cert.events?.[0]?.title || 'Event'}"</p>
                          <p className="text-xs text-gray-500">{new Date(cert.generated_at).toLocaleDateString()} • {new Date(cert.generated_at).toLocaleTimeString()}</p>
                        </div>
                      </div>
                    ))
                  ) : (
                    <div className="text-center py-4 text-gray-500">
                      <Award className="h-8 w-8 mx-auto mb-2 text-gray-300" />
                      <p className="text-sm">No recent certificate activity</p>
                    </div>
                  )}
                  
                  {activity.recentTemplates.length > 0 && (
                    <div className="flex items-center gap-3 p-3 bg-blue-50 rounded-lg border border-blue-200">
                      <div className="w-8 h-8 bg-blue-500 rounded-full flex items-center justify-center">
                        <FolderOpen className="h-4 w-4 text-white" />
                      </div>
                      <div className="flex-1">
                        <p className="text-sm font-medium text-gray-900">Template "{activity.recentTemplates[0].name}" created</p>
                        <p className="text-xs text-gray-500">{new Date(activity.recentTemplates[0].created_at).toLocaleDateString()}</p>
                      </div>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>

            {/* Stats Dashboard */}
            <Card data-tour="certificates-statistics">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Star className="h-5 w-5 text-yellow-600" />
                  Statistics
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                    <div className="flex items-center gap-2">
                      <Award className="h-4 w-4 text-green-600" />
                      <span className="text-sm font-medium">Total Generated</span>
                    </div>
                    <Badge variant="secondary" className="bg-green-100 text-green-700">{stats.totalCertificates}</Badge>
                  </div>
                  
                  <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                    <div className="flex items-center gap-2">
                      <FolderOpen className="h-4 w-4 text-blue-600" />
                      <span className="text-sm font-medium">Active Templates</span>
                    </div>
                    <Badge variant="secondary" className="bg-blue-100 text-blue-700">{stats.totalTemplates}</Badge>
                  </div>
                  
                  <div className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                    <div className="flex items-center gap-2">
                      <Calendar className="h-4 w-4 text-purple-600" />
                      <span className="text-sm font-medium">Events with Certificates</span>
                    </div>
                    <Badge variant="secondary" className="bg-purple-100 text-purple-700">{stats.eventsWithCertificates}</Badge>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Template Gallery - Shared by Others */}
        {sharedTemplates.length > 0 && (
          <div className="mb-12" data-tour="certificates-template-gallery">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Users className="h-5 w-5 text-blue-600" />
                  Template Gallery
                </CardTitle>
                <CardDescription>Templates shared by other users in your organization</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {sharedTemplates.map((template: any) => (
                    <Card key={template.id} className="border-2 border-blue-200 bg-gradient-to-br from-blue-50 to-indigo-50 hover:shadow-lg hover:scale-[1.02] transition-all duration-300">
                      <CardContent className="p-4">
                        <div className="flex items-start justify-between mb-3">
                          <div className="flex-1 min-w-0">
                            <h3 className="font-semibold text-blue-900 mb-1 truncate">{template.name}</h3>
                            <p className="text-sm text-blue-700 truncate">Shared by {template.users?.name || 'Unknown'}</p>
                          </div>
                          <Badge variant="secondary" className="bg-blue-100 text-blue-700 text-xs flex-shrink-0 ml-2">
                            Shared
                          </Badge>
                        </div>
                        
                        <div className="space-y-1 mb-3">
                          <div className="text-xs text-blue-600">
                            Created: {new Date(template.created_at).toLocaleDateString()}
                          </div>
                          {template.shared_at && (
                            <div className="text-xs text-blue-600">
                              Shared: {new Date(template.shared_at).toLocaleDateString()}
                            </div>
                          )}
                        </div>
                        
                        <Button asChild className="w-full bg-blue-600 hover:bg-blue-700 text-white hover:text-white text-sm">
                          <Link href={`/certificates/image-builder?template=${template.id}`}>
                            <Eye className="h-4 w-4 mr-2" />
                            View Template
                          </Link>
                        </Button>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Featured Templates */}
        <div className="mb-12" data-tour="certificates-featured-templates">
          <div className="grid grid-cols-1 gap-6">
            {/* Featured Templates */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Star className="h-5 w-5 text-yellow-600" />
                  Featured Templates
                </CardTitle>
                <CardDescription>Most popular shared templates</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-3">
                  {featuredTemplates.length > 0 ? (
                    featuredTemplates.map((template: any, index: number) => {
                      const colors = [
                        { bg: 'from-blue-50 to-indigo-50', border: 'border-blue-200', icon: 'bg-blue-500' },
                        { bg: 'from-green-50 to-emerald-50', border: 'border-green-200', icon: 'bg-green-500' },
                        { bg: 'from-purple-50 to-pink-50', border: 'border-purple-200', icon: 'bg-purple-500' }
                      ]
                      const icons = [Award, FileText, Users]
                      const IconComponent = icons[index % icons.length]
                      const colorScheme = colors[index % colors.length]
                      
                      return (
                        <div key={template.id} className={`p-4 bg-gradient-to-r ${colorScheme.bg} rounded-lg border ${colorScheme.border} space-y-3`}>
                          <div className="flex items-center gap-3">
                            <div className={`w-12 h-12 ${colorScheme.icon} rounded-lg flex items-center justify-center`}>
                              <IconComponent className="h-6 w-6 text-white" />
                            </div>
                            <div className="flex-1 min-w-0">
                              <h4 className="font-semibold text-gray-900 truncate">{template.name}</h4>
                              <p className="text-sm text-gray-600 truncate">Shared by {template.users?.name || 'Unknown'}</p>
                            </div>
                          </div>
                          <Button asChild size="sm" variant="outline" className="w-full">
                            <Link href={`/certificates/image-builder?use=${template.id}`}>
                              <Eye className="h-4 w-4 mr-2" />
                              Use Template
                            </Link>
                          </Button>
                        </div>
                      )
                    })
                  ) : (
                    <div className="text-center py-8">
                      <Star className="h-12 w-12 mx-auto text-gray-300 mb-4" />
                      <p className="text-gray-500">No featured templates available yet</p>
                      <p className="text-sm text-gray-400 mt-2">Create and share templates to see them here</p>
                    </div>
                  )}
                </div>
                
                <Button asChild variant="outline" className="w-full">
                  <Link href="/certificates/templates">
                    View All Templates
                    <ArrowRight className="h-4 w-4 ml-2" />
                  </Link>
                </Button>
              </CardContent>
            </Card>

          </div>
        </div>

        {/* Divider */}
        <div className="mb-12">
          <div className="border-t border-gray-200"></div>
        </div>

        {/* Two Main Paths */}
        <div className="mb-12">
          <div className="text-center mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Choose Your Path</h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Whether you're creating your first certificate or using an existing template, we've got you covered.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-8">
            {/* Path 1: Create New */}
            <Card className="border-2 border-green-200 hover:border-green-300 transition-colors" data-tour="certificates-create-new-detailed">
              <CardHeader className="bg-gradient-to-r from-green-50 to-emerald-50">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-green-500 rounded-lg flex items-center justify-center">
                    <Plus className="h-6 w-6 text-white" />
                  </div>
                  <div>
                    <CardTitle className="text-green-900">Create New Certificate</CardTitle>
                    <p className="text-sm text-green-700">Start from scratch with full customization</p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-6">
                <div className="space-y-4">
                  <div className="flex items-start gap-3">
                    <CheckCircle className="h-5 w-5 text-green-600 mt-0.5 flex-shrink-0" />
                    <div>
                      <h4 className="font-medium text-gray-900">Full Design Control</h4>
                      <p className="text-sm text-gray-600">Upload any background image and customize every detail</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <CheckCircle className="h-5 w-5 text-green-600 mt-0.5 flex-shrink-0" />
                    <div>
                      <h4 className="font-medium text-gray-900">Dynamic Data Fields</h4>
                      <p className="text-sm text-gray-600">Real event and attendee data automatically populates</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <CheckCircle className="h-5 w-5 text-green-600 mt-0.5 flex-shrink-0" />
                    <div>
                      <h4 className="font-medium text-gray-900">Save as Template</h4>
                      <p className="text-sm text-gray-600">Reuse your design for future events</p>
                    </div>
                  </div>
                </div>
                <div className="mt-6">
                  <Button asChild className="w-full bg-green-600 hover:bg-green-700 text-white hover:text-white">
                    <Link href="/certificates/select-event">
                      <Plus className="h-4 w-4 mr-2" />
                      Start Creating
                    </Link>
                  </Button>
                </div>
              </CardContent>
            </Card>

            {/* Path 2: Use Template */}
            <Card className="border-2 border-blue-200 hover:border-blue-300 transition-colors" data-tour="certificates-use-template-detailed">
              <CardHeader className="bg-gradient-to-r from-blue-50 to-indigo-50">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 bg-blue-500 rounded-lg flex items-center justify-center">
                    <Sparkles className="h-6 w-6 text-white" />
                  </div>
                  <div>
                    <CardTitle className="text-blue-900">Use Existing Template</CardTitle>
                    <p className="text-sm text-blue-700">Quick generation with saved templates</p>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="p-6">
                <div className="space-y-4">
                  <div className="flex items-start gap-3">
                    <CheckCircle className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
                    <div>
                      <h4 className="font-medium text-gray-900">Instant Generation</h4>
                      <p className="text-sm text-gray-600">Use pre-designed templates for quick results</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <CheckCircle className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
                    <div>
                      <h4 className="font-medium text-gray-900">Bulk Processing</h4>
                      <p className="text-sm text-gray-600">Generate certificates for all attendees at once</p>
                    </div>
                  </div>
                  <div className="flex items-start gap-3">
                    <CheckCircle className="h-5 w-5 text-blue-600 mt-0.5 flex-shrink-0" />
                    <div>
                      <h4 className="font-medium text-gray-900">Auto Email Delivery</h4>
                      <p className="text-sm text-gray-600">Certificates sent automatically to attendees</p>
                    </div>
                  </div>
                </div>
                <div className="mt-6">
                  <Button asChild className="w-full bg-blue-600 hover:bg-blue-700 text-white hover:text-white">
                    <Link href="/certificates/generate">
                      <Sparkles className="h-4 w-4 mr-2" />
                      Generate Now
                    </Link>
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* Divider */}
        <div className="mb-12">
          <div className="border-t border-gray-200"></div>
        </div>

        {/* Management Tools */}
        <div className="mb-12" data-tour="certificates-management-tools">
          <div className="text-center mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Management Tools</h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Manage your templates and certificates with our powerful tools.
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card className="hover:shadow-lg hover:scale-[1.02] transition-all duration-300 border-blue-200">
              <CardHeader className="bg-blue-50">
                <CardTitle className="flex items-center gap-2 text-blue-900">
                  <FolderOpen className="h-5 w-5" />
                  Template Library
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-sm text-gray-600 mb-4">
                  Browse and manage your saved certificate templates.
                </p>
                <Button asChild variant="outline" className="w-full border-blue-300 text-blue-700 hover:bg-blue-100 hover:border-blue-400 hover:text-blue-800">
                  <Link href="/certificates/templates">
                    <FolderOpen className="h-4 w-4 mr-2" />
                    Manage Templates
                  </Link>
                </Button>
              </CardContent>
            </Card>

            <Card className="hover:shadow-lg hover:scale-[1.02] transition-all duration-300 border-green-200">
              <CardHeader className="bg-green-50">
                <CardTitle className="flex items-center gap-2 text-green-900">
                  <Settings className="h-5 w-5" />
                  Certificate Manager
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-sm text-gray-600 mb-4">
                  View, manage, and resend generated certificates.
                </p>
                <Button asChild variant="outline" className="w-full border-green-300 text-green-700 hover:bg-green-100 hover:border-green-400 hover:text-green-800">
                  <Link href="/certificates/manage">
                    <Settings className="h-4 w-4 mr-2" />
                    Manage Certificates
                  </Link>
                </Button>
              </CardContent>
            </Card>

            <Card className="hover:shadow-lg hover:scale-[1.02] transition-all duration-300 border-purple-200">
              <CardHeader className="bg-purple-50">
                <CardTitle className="flex items-center gap-2 text-purple-900">
                  <Award className="h-5 w-5" />
                  My Certificates
                </CardTitle>
              </CardHeader>
              <CardContent className="p-4">
                <p className="text-sm text-gray-600 mb-4">
                  View and download certificates you've received.
                </p>
                <Button asChild variant="outline" className="w-full border-purple-300 text-purple-700 hover:bg-purple-100 hover:border-purple-400 hover:text-purple-800">
                  <Link href="/mycertificates">
                    <Award className="h-4 w-4 mr-2" />
                    View My Certificates
                  </Link>
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>

        {/* FAQs Section */}
        <div className="mb-12">
          <div className="text-center mb-8">
            <h2 className="text-2xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h2>
            <p className="text-gray-600 max-w-2xl mx-auto">
              Everything you need to know about creating and managing certificates.
            </p>
          </div>

          <div className="max-w-4xl mx-auto space-y-6">
            {/* FAQ 1 */}
            <Card className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300">
              <details className="group">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gradient-to-r hover:from-blue-50 hover:to-indigo-50 transition-all duration-300 rounded-lg">
                  <h3 className="font-semibold text-gray-900 text-lg">How do I create a new certificate template?</h3>
                  <ChevronDown className="h-6 w-6 text-gray-500 group-open:rotate-180 transition-transform duration-300" />
                </summary>
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 pt-6">
                    <div className="bg-blue-50 p-4 rounded-lg mb-4">
                      <p className="text-gray-700 font-medium mb-3">
                        Follow these simple steps to create your certificate template:
                      </p>
                      <ol className="list-decimal list-inside text-gray-600 space-y-3">
                        <li className="flex items-start"><span className="font-medium mr-2">1.</span> Click "Create New" in the Quick Actions section</li>
                        <li className="flex items-start"><span className="font-medium mr-2">2.</span> Select an event with enabled booking configuration</li>
                        <li className="flex items-start"><span className="font-medium mr-2">3.</span> Upload your certificate background image</li>
                        <li className="flex items-start"><span className="font-medium mr-2">4.</span> Add text fields and position them on your template</li>
                        <li className="flex items-start"><span className="font-medium mr-2">5.</span> Save your template with a descriptive name</li>
                        <li className="flex items-start"><span className="font-medium mr-2">6.</span> Optionally share it with others by checking the "Share with others" box</li>
                      </ol>
                    </div>
                  </div>
                </div>
              </details>
            </Card>

            {/* FAQ 2 */}
            <Card className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300">
              <details className="group">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gradient-to-r hover:from-green-50 hover:to-emerald-50 transition-all duration-300 rounded-lg">
                  <h3 className="font-semibold text-gray-900 text-lg">How do I generate certificates for attendees?</h3>
                  <ChevronDown className="h-6 w-6 text-gray-500 group-open:rotate-180 transition-transform duration-300" />
                </summary>
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 pt-6">
                    <div className="bg-green-50 p-4 rounded-lg mb-4">
                      <p className="text-gray-700 font-medium mb-3">
                        Generate certificates for your event attendees:
                      </p>
                      <ol className="list-decimal list-inside text-gray-600 space-y-3">
                        <li className="flex items-start"><span className="font-medium mr-2">1.</span> Click "Generate Now" in the Quick Actions section</li>
                        <li className="flex items-start"><span className="font-medium mr-2">2.</span> Select the event you want to generate certificates for</li>
                        <li className="flex items-start"><span className="font-medium mr-2">3.</span> Choose a template from your Template Library</li>
                        <li className="flex items-start"><span className="font-medium mr-2">4.</span> Review the attendee list and select who should receive certificates</li>
                        <li className="flex items-start"><span className="font-medium mr-2">5.</span> Click "Generate Certificates" to create and save them</li>
                        <li className="flex items-start"><span className="font-medium mr-2">6.</span> Certificates will be automatically saved to Supabase Storage</li>
                      </ol>
                    </div>
                  </div>
                </div>
              </details>
            </Card>

            {/* FAQ 3 */}
            <Card className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300">
              <details className="group">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gradient-to-r hover:from-purple-50 hover:to-pink-50 transition-all duration-300 rounded-lg">
                  <h3 className="font-semibold text-gray-900 text-lg">How does the sharing system work?</h3>
                  <ChevronDown className="h-6 w-6 text-gray-500 group-open:rotate-180 transition-transform duration-300" />
                </summary>
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 pt-6">
                    <div className="bg-purple-50 p-4 rounded-lg mb-4">
                      <p className="text-gray-700 font-medium mb-3">
                        Our template sharing system works with role-based access:
                      </p>
                      <ul className="list-disc list-inside text-gray-600 space-y-3">
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Admins:</strong> Can see all certificates and templates</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>CTF, MedEd Team, Educators:</strong> Can see their own templates and shared templates from others</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Students:</strong> Can only see shared templates</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span>When you check "Share with others", your template becomes visible to users with appropriate roles</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span>Shared templates appear in the "Featured Templates" section</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </details>
            </Card>

            {/* FAQ 4 */}
            <Card className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300">
              <details className="group">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gradient-to-r hover:from-orange-50 hover:to-amber-50 transition-all duration-300 rounded-lg">
                  <h3 className="font-semibold text-gray-900 text-lg">How do I manage my templates and certificates?</h3>
                  <ChevronDown className="h-6 w-6 text-gray-500 group-open:rotate-180 transition-transform duration-300" />
                </summary>
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 pt-6">
                    <div className="bg-orange-50 p-4 rounded-lg mb-4">
                      <p className="text-gray-700 font-medium mb-3">
                        You can manage your content through these sections:
                      </p>
                      <ul className="list-disc list-inside text-gray-600 space-y-3">
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Template Library:</strong> View, edit, delete, and share your certificate templates</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Certificate Manager:</strong> View and manage all generated certificates</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>My Certificates:</strong> View certificates you've received as an attendee</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span>Templates are organized by user in Supabase Storage under "User &gt; template-images"</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span>Certificates are stored as "User &gt; Attendee name &gt; Certificate file"</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </details>
            </Card>

            {/* FAQ 5 */}
            <Card className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300">
              <details className="group">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gradient-to-r hover:from-indigo-50 hover:to-blue-50 transition-all duration-300 rounded-lg">
                  <h3 className="font-semibold text-gray-900 text-lg">What file formats are supported for certificate images?</h3>
                  <ChevronDown className="h-6 w-6 text-gray-500 group-open:rotate-180 transition-transform duration-300" />
                </summary>
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 pt-6">
                    <div className="bg-indigo-50 p-4 rounded-lg mb-4">
                      <p className="text-gray-700 font-medium mb-3">
                        Supported image formats for certificate templates:
                      </p>
                      <ul className="list-disc list-inside text-gray-600 space-y-3">
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>PNG:</strong> Recommended for certificates with transparency</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>JPG/JPEG:</strong> Good for photographs and complex images</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>WebP:</strong> Modern format with good compression</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span>Images are stored in Supabase Storage for optimal performance</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span>Maximum recommended size: 1920x1080 pixels for best quality</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </details>
            </Card>

            {/* FAQ 6 */}
            <Card className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300">
              <details className="group">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gradient-to-r hover:from-teal-50 hover:to-cyan-50 transition-all duration-300 rounded-lg">
                  <h3 className="font-semibold text-gray-900 text-lg">How do I edit an existing template?</h3>
                  <ChevronDown className="h-6 w-6 text-gray-500 group-open:rotate-180 transition-transform duration-300" />
                </summary>
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 pt-6">
                    <div className="bg-teal-50 p-4 rounded-lg mb-4">
                      <p className="text-gray-700 font-medium mb-3">
                        To edit an existing template:
                      </p>
                      <ol className="list-decimal list-inside text-gray-600 space-y-3">
                        <li className="flex items-start"><span className="font-medium mr-2">1.</span> Go to "Template Library" in the Quick Actions</li>
                        <li className="flex items-start"><span className="font-medium mr-2">2.</span> Find the template you want to edit</li>
                        <li className="flex items-start"><span className="font-medium mr-2">3.</span> Click "Edit this template" button</li>
                        <li className="flex items-start"><span className="font-medium mr-2">4.</span> Make your changes to text fields, positions, or background</li>
                        <li className="flex items-start"><span className="font-medium mr-2">5.</span> Click "Save Changes" to update the template</li>
                        <li className="flex items-start"><span className="font-medium mr-2">6.</span> The template will be updated and any shared versions will reflect your changes</li>
                      </ol>
                    </div>
                  </div>
                </div>
              </details>
            </Card>

            {/* FAQ 7 - NEW */}
            <Card className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300">
              <details className="group">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gradient-to-r hover:from-rose-50 hover:to-pink-50 transition-all duration-300 rounded-lg">
                  <h3 className="font-semibold text-gray-900 text-lg">What are the coordinate matching and scaling features?</h3>
                  <ChevronDown className="h-6 w-6 text-gray-500 group-open:rotate-180 transition-transform duration-300" />
                </summary>
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 pt-6">
                    <div className="bg-rose-50 p-4 rounded-lg mb-4">
                      <p className="text-gray-700 font-medium mb-3">
                        Our certificate system includes advanced coordinate matching:
                      </p>
                      <ul className="list-disc list-inside text-gray-600 space-y-3">
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Preview Accuracy:</strong> Text fields in the preview match exactly with the generated certificate</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Smart Scaling:</strong> Automatic scaling from template dimensions to final image size</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Precise Positioning:</strong> Text appears exactly where you place it in the template builder</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Font Scaling:</strong> Font sizes are automatically adjusted to maintain readability</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>Alignment Support:</strong> Left, center, and right text alignment with proper positioning</li>
                        <li className="flex items-start"><span className="font-medium mr-2">•</span><strong>High-Quality Output:</strong> Generated certificates maintain crisp text at any resolution</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </details>
            </Card>

            {/* FAQ 8 - NEW */}
            <Card className="border border-gray-200 shadow-sm hover:shadow-md transition-shadow duration-300">
              <details className="group">
                <summary className="flex items-center justify-between p-6 cursor-pointer hover:bg-gradient-to-r hover:from-violet-50 hover:to-purple-50 transition-all duration-300 rounded-lg">
                  <h3 className="font-semibold text-gray-900 text-lg">How do I use featured templates from other users?</h3>
                  <ChevronDown className="h-6 w-6 text-gray-500 group-open:rotate-180 transition-transform duration-300" />
                </summary>
                <div className="px-6 pb-6">
                  <div className="border-t border-gray-200 pt-6">
                    <div className="bg-violet-50 p-4 rounded-lg mb-4">
                      <p className="text-gray-700 font-medium mb-3">
                        Using featured templates is easy:
                      </p>
                      <ol className="list-decimal list-inside text-gray-600 space-y-3">
                        <li className="flex items-start"><span className="font-medium mr-2">1.</span> Browse the "Featured Templates" section on the main certificates page</li>
                        <li className="flex items-start"><span className="font-medium mr-2">2.</span> Click "Use" on any template you like</li>
                        <li className="flex items-start"><span className="font-medium mr-2">3.</span> The template will load in the image builder with all text fields and styling</li>
                        <li className="flex items-start"><span className="font-medium mr-2">4.</span> You can customize the text fields, positions, and styling as needed</li>
                        <li className="flex items-start"><span className="font-medium mr-2">5.</span> Click "Generate Certificate" to proceed to certificate generation</li>
                        <li className="flex items-start"><span className="font-medium mr-2">6.</span> Select your event and generate certificates for attendees</li>
                        <li className="flex items-start"><span className="font-medium mr-2">7.</span> The template will be saved to your personal template library for future use</li>
                      </ol>
                    </div>
                  </div>
                </div>
              </details>
            </Card>
          </div>
        </div>

    </div>
  )
}