import https from 'https';
import {
  buildAccountApprovalEmail,
  buildAccountCreatedEmail,
  buildAdminContactFormEmail,
  buildAdminFileRequestEmail,
  buildAdminMededTeamProfileEmail,
  buildAdminNewUserEmail,
  buildAdminTeachingRequestEmail,
  buildAttendanceThankYouEmail,
  buildCertificateAutoGeneratedEmail,
  buildCertificateEmail,
  buildConnectionAcceptedEmail,
  buildConnectionReportAcknowledgementEmail,
  buildConnectionReportEmail,
  buildConnectionRequestEmail,
  buildFeedbackFormEmail,
  buildAdminLoginLockoutEmail,
  buildLoginLockoutEmail,
  buildPasswordChangedEmail,
  buildPasswordResetEmail,
  buildRoleChangeEmail,
  buildVerificationEmail,
} from '@/lib/email-templates/system'


// Cache for storing access token and expiry
let tokenCache = {
  accessToken: null as string | null,
  expiresAt: null as number | null
};

// Resolve application base URL robustly for links in emails
const getAppBaseUrl = (): string => {
  const fromEnv = process.env.NEXT_PUBLIC_APP_URL;
  if (fromEnv && fromEnv.trim().length > 0) {
    const url = fromEnv.trim();
    // Never put localhost / preview hosts in outbound email links
    if (/localhost|127\.0\.0\.1|0\.0\.0\.0|vercel\.app/i.test(url)) {
      return 'https://sim.bleepy.co.uk';
    }
    return url;
  }
  // Default to production domain instead of Vercel URL
  return 'https://sim.bleepy.co.uk';
};

// Get fresh access token from Microsoft Entra ID
const getFreshAccessToken = async (): Promise<string> => {
  return new Promise((resolve, reject) => {
    const tokenUrl = `https://login.microsoftonline.com/${process.env.AZURE_TENANT_ID}/oauth2/v2.0/token`;
    
    const postData = new URLSearchParams({
      client_id: process.env.AZURE_CLIENT_ID!,
      client_secret: process.env.AZURE_CLIENT_SECRET!,
      scope: 'https://graph.microsoft.com/.default',
      grant_type: 'client_credentials'
    });

    const options = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': Buffer.byteLength(postData.toString())
      }
    };

    const req = https.request(tokenUrl, options, (res) => {
      let data = '';
      
      res.on('data', (chunk) => {
        data += chunk;
      });
      
      res.on('end', () => {
        try {
          const response = JSON.parse(data);
          if (response.access_token) {
            // Cache the token with expiry time
            tokenCache.accessToken = response.access_token;
            tokenCache.expiresAt = Date.now() + (response.expires_in * 1000) - 60000; // 1 minute buffer
            resolve(response.access_token);
          } else {
            reject(new Error(`Token request failed: ${data}`));
          }
        } catch (error) {
          reject(new Error(`Failed to parse token response: ${error}`));
        }
      });
    });
    
    req.on('error', (error) => {
      reject(error);
    });
    
    req.write(postData.toString());
    req.end();
  });
};

// Get valid access token (refresh if needed)
const getValidAccessToken = async (): Promise<string> => {
  // Check if we have a valid cached token
  if (tokenCache.accessToken && tokenCache.expiresAt && Date.now() < tokenCache.expiresAt) {
    return tokenCache.accessToken;
  }
  
  // Get fresh token
  console.log('Getting fresh Azure access token...');
  return await getFreshAccessToken();
};

// Email validation function
const isValidEmail = (email: string): boolean => {
  const emailRegex = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
  return emailRegex.test(email.trim());
};

export type EmailAttachment = {
  name: string
  contentType: string
  /** Base64-encoded file contents (Graph API contentBytes) */
  contentBytes: string
  /** When set with isInline, reference from HTML as cid:{contentId} */
  contentId?: string
  isInline?: boolean
}

// Send email using Microsoft Graph API with automatic token refresh and improved error handling
const sendEmailViaGraphAPI = async (
  to: string,
  subject: string,
  htmlContent: string,
  attachments?: EmailAttachment[]
) => {
  return new Promise(async (resolve, reject) => {
    try {
      // Validate email format
      if (!isValidEmail(to)) {
        const error = new Error(`Invalid email format: ${to}`);
        console.error('Email validation failed:', error.message);
        reject(error);
        return;
      }

      // Get valid access token
      const accessToken = await getValidAccessToken();
      
      const graphUrl = `https://graph.microsoft.com/v1.0/users/${process.env.SMTP_USER}/sendMail`;
      
      const messagePayload: {
        message: Record<string, unknown>
      } = {
        message: {
          subject: subject,
          body: {
            contentType: 'HTML',
            content: htmlContent
          },
          toRecipients: [
            {
              emailAddress: {
                address: to.trim()
              }
            }
          ]
        }
      };

      if (attachments && attachments.length > 0) {
        messagePayload.message.attachments = attachments.map((file) => ({
          '@odata.type': '#microsoft.graph.fileAttachment',
          name: file.name,
          contentType: file.contentType,
          contentBytes: file.contentBytes,
          ...(file.contentId
            ? {
                contentId: file.contentId,
                isInline: file.isInline !== false,
              }
            : {}),
        }))
      }

      const postData = JSON.stringify(messagePayload);

      const options = {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${accessToken}`,
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(postData)
        }
      };

      console.log(`Sending email to: ${to}, subject: ${subject}`);

      const req = https.request(graphUrl, options, (res) => {
        let data = '';
        
        res.on('data', (chunk) => {
          data += chunk;
        });
        
        res.on('end', () => {
          console.log(`Email API response for ${to}:`, {
            statusCode: res.statusCode,
            headers: res.headers,
            body: data
          });

          if (res.statusCode === 202) {
            const messageId = res.headers['x-ms-request-id'];
            console.log(`Email sent successfully to ${to}, messageId: ${messageId}`);
            resolve({ 
              success: true, 
              messageId,
              recipient: to,
              statusCode: res.statusCode
            });
          } else {
            const error = new Error(`HTTP ${res.statusCode}: ${data}`);
            console.error(`Email delivery failed for ${to}:`, {
              statusCode: res.statusCode,
              response: data,
              recipient: to
            });
            reject(error);
          }
        });
      });
      
      req.on('error', (error) => {
        console.error(`Network error sending email to ${to}:`, error);
        reject(error);
      });
      
      req.write(postData);
      req.end();
    } catch (error) {
      console.error(`Error in sendEmailViaGraphAPI for ${to}:`, error);
      reject(error);
    }
  });
};

export interface EmailVerificationData {
  email: string;
  name: string;
  verificationUrl: string;
}

export interface PasswordResetData {
  email: string;
  name: string;
  resetUrl: string;
}

export async function sendVerificationEmail(data: EmailVerificationData) {
  try {
    const mail = buildVerificationEmail(data)
    const result = await sendEmailViaGraphAPI(data.email, mail.subject, mail.html);
    console.log('Verification email sent via Graph API:', result);
    
    return result;
  } catch (error) {
    console.error('Email sending error:', error);
    throw new Error('Failed to send verification email');
  }
}

export async function sendPasswordResetEmail(data: PasswordResetData) {
  try {
    const mail = buildPasswordResetEmail(data)
    const result = await sendEmailViaGraphAPI(data.email, mail.subject, mail.html);
    console.log('Password reset email sent via Graph API:', result);
    
    return result;
  } catch (error) {
    console.error('Email sending error:', error);
    throw new Error('Failed to send password reset email');
  }
}

export async function sendPasswordChangedEmail(data: { email: string; name: string }) {
  try {
    const mail = buildPasswordChangedEmail({
      name: data.name,
      signInUrl: `${getAppBaseUrl()}/auth/signin`,
      resetUrl: `${getAppBaseUrl()}/auth/forgot-password`,
    })
    return await sendEmailWithRetry(data.email, mail.subject, mail.html)
  } catch (error) {
    console.error('Password changed email failed:', error)
    return false
  }
}

export interface AccountApprovalData {
  email: string;
  name: string;
}

export interface RoleChangeData {
  email: string;
  name: string;
  oldRole: string;
  newRole: string;
}

export interface AccountCreatedData {
  name: string;
  email: string;
  role: string;
  password: string;
  loginUrl: string;
}

// Retry mechanism for email sending
export const sendEmailWithRetry = async (
  to: string,
  subject: string,
  htmlContent: string,
  maxRetries = 2,
  attachments?: EmailAttachment[]
) => {
  let lastError: Error | null = null;
  
  for (let attempt = 1; attempt <= maxRetries; attempt++) {
    try {
      console.log(`Email attempt ${attempt}/${maxRetries} for ${to}`);
      const result = await sendEmailViaGraphAPI(to, subject, htmlContent, attachments);
      console.log(`Email sent successfully on attempt ${attempt} to ${to}`);
      return result;
    } catch (error) {
      lastError = error as Error;
      console.error(`Email attempt ${attempt} failed for ${to}:`, error);
      
      if (attempt < maxRetries) {
        const delay = Math.pow(2, attempt) * 1000; // Exponential backoff
        console.log(`Retrying email to ${to} in ${delay}ms...`);
        await new Promise(resolve => setTimeout(resolve, delay));
      }
    }
  }
  
  throw lastError || new Error('Email sending failed after all retries');
};

export async function sendCustomHtmlEmail(
  to: string,
  subject: string,
  htmlContent: string,
  attachments?: EmailAttachment[]
) {
  return sendEmailWithRetry(to, subject, htmlContent, 2, attachments);
}

export async function sendAccountApprovalEmail(data: AccountApprovalData) {
  try {
    console.log(`Sending account approval email to: ${data.email}`)
    const mail = buildAccountApprovalEmail(data)
    const result = await sendEmailWithRetry(data.email, mail.subject, mail.html)
    console.log('Account approval email sent successfully:', result)
    return result
  } catch (error) {
    console.error('Account approval email failed:', error)
    throw new Error(`Failed to send account approval email to ${data.email}: ${error}`)
  }
}

const ADMIN_INBOX = 'drvarun1995@gmail.com'

export async function sendLoginLockoutNotifications(data: {
  email: string
  userName?: string | null
  userExists: boolean
  ip?: string | null
  lockoutMinutes: number
  maxAttempts: number
  windowMinutes: number
}) {
  const signInUrl = `${getAppBaseUrl()}/auth/signin`
  const resetUrl = `${getAppBaseUrl()}/auth/forgot-password`
  try {
    const adminMail = buildAdminLoginLockoutEmail(data)
    await sendEmailViaGraphAPI(ADMIN_INBOX, adminMail.subject, adminMail.html)
  } catch (error) {
    console.error('Admin login lockout email failed:', error)
  }

  if (!data.userExists) return

  try {
    const userMail = buildLoginLockoutEmail({
      name: data.userName || data.email,
      lockoutMinutes: data.lockoutMinutes,
      resetUrl,
      signInUrl,
    })
    await sendEmailWithRetry(data.email, userMail.subject, userMail.html)
  } catch (error) {
    console.error('User login lockout email failed:', error)
  }
}

export async function sendRoleChangeEmail(data: RoleChangeData) {
  try {
    console.log(`Sending role change email to: ${data.email}`)
    const mail = buildRoleChangeEmail(data)
    const result = await sendEmailWithRetry(data.email, mail.subject, mail.html)
    console.log('Role change email sent successfully:', result)
    return result
  } catch (error) {
    console.error('Role change email failed:', error)
    throw new Error(`Failed to send role change email to ${data.email}: ${error}`)
  }
}

export async function sendAdminContactFormNotification(data: {
  contactId: string
  name: string
  email: string
  subject: string
  category: string
  message: string
  submissionTime: string
}) {
  try {
    const mail = buildAdminContactFormEmail(data)
    await sendEmailViaGraphAPI(ADMIN_INBOX, mail.subject, mail.html)
    console.log(`Contact form notification sent to admin for message: ${data.contactId}`)
    return true
  } catch (error) {
    console.error('Failed to send contact form notification:', error)
    return false
  }
}

export const sendAdminFileRequestNotification = async (data: {
  requestId: string
  userName: string
  userEmail: string
  fileName: string
  description: string
  preferredFormat?: string
  additionalInfo?: string
  eventTitle: string
  eventDate?: string
  submissionTime: string
}) => {
  try {
    const mail = buildAdminFileRequestEmail(data)
    await sendEmailViaGraphAPI(ADMIN_INBOX, mail.subject, mail.html)
    console.log(`File request notification sent to admin for request: ${data.requestId}`)
    return true
  } catch (error) {
    console.error('Failed to send file request notification:', error)
    return false
  }
}

export const sendAdminTeachingRequestNotification = async (data: {
  requestId: string
  userName: string
  userEmail: string
  topic: string
  description: string
  preferredDate?: string
  preferredTime?: string
  duration: string
  categories: string[]
  format: string
  additionalInfo?: string
  submissionTime: string
}) => {
  try {
    const mail = buildAdminTeachingRequestEmail(data)
    await sendEmailViaGraphAPI(ADMIN_INBOX, mail.subject, mail.html)
    console.log(`Teaching request notification sent to admin for request: ${data.requestId}`)
    return true
  } catch (error) {
    console.error('Failed to send teaching request notification:', error)
    return false
  }
}

export async function sendAccountCreatedEmail(data: AccountCreatedData) {
  try {
    console.log(`Sending account created email to: ${data.email}`)
    const mail = buildAccountCreatedEmail(data)
    const result = await sendEmailWithRetry(data.email, mail.subject, mail.html)
    console.log('Account created email sent successfully:', result)
    return result
  } catch (error) {
    console.error('Account created email failed:', error)
    throw new Error(`Failed to send account created email to ${data.email}: ${error}`)
  }
}

export const sendAdminMededTeamProfileNotification = async (data: {
  userName: string
  userEmail: string
  publicSlug: string | null
}) => {
  try {
    const mail = buildAdminMededTeamProfileEmail(data)
    await sendEmailViaGraphAPI(ADMIN_INBOX, mail.subject, mail.html)
    return true
  } catch (error) {
    console.error('Failed to send MedEd team profile notification email:', error)
    return false
  }
}

export async function sendAdminNewUserNotification(data: {
  userEmail: string
  userName: string
  signupTime: string
  consentGiven: boolean
  marketingConsent: boolean
  analyticsConsent: boolean
}) {
  try {
    const mail = buildAdminNewUserEmail(data)
    const result = await sendEmailViaGraphAPI(ADMIN_INBOX, mail.subject, mail.html)
    console.log('Admin notification email sent:', result)
    return result
  } catch (error) {
    console.error('Admin notification email error:', error)
    throw new Error('Failed to send admin notification email')
  }
}

export interface CertificateEmailData {
  recipientEmail: string
  recipientName: string
  eventTitle: string
  eventDate: string
  eventLocation?: string
  eventDuration?: string
  certificateUrl: string
  certificateId: string
  isGuestAccess?: boolean
  certificateStoragePath?: string | null
  certificateFilename?: string | null
}

export async function sendCertificateEmail(data: CertificateEmailData) {
  try {
    console.log(`Sending certificate email to: ${data.recipientEmail}`)
    const { loadCertificateEmailAttachment } = await import('@/lib/certificate-attachment')
    const attachment = await loadCertificateEmailAttachment(
      data.certificateStoragePath,
      data.certificateFilename
    )
    const mail = buildCertificateEmail({
      ...data,
      certificateUrl: data.certificateUrl || `${getAppBaseUrl()}/mycertificates`,
      hasAttachment: !!attachment,
    })
    const result = await sendEmailWithRetry(
      data.recipientEmail,
      mail.subject,
      mail.html,
      2,
      attachment ? [attachment] : undefined
    )
    console.log('Certificate email sent successfully:', result, { attached: !!attachment })
    return result
  } catch (error) {
    console.error('Certificate email failed:', error)
    throw new Error(`Failed to send certificate email to ${data.recipientEmail}: ${error}`)
  }
}

export const sendFeedbackFormEmail = async (data: {
  recipientEmail: string
  recipientName: string
  eventTitle: string
  eventDate: string
  eventTime: string
  feedbackFormUrl: string
  feedbackRequiredForCertificate?: boolean
  isGuestAccess?: boolean
}) => {
  const mail = buildFeedbackFormEmail(data)
  return sendEmailWithRetry(data.recipientEmail, mail.subject, mail.html)
}

export const sendCertificateAutoGeneratedEmail = async (data: {
  recipientEmail: string
  recipientName: string
  eventTitle: string
  eventDate: string
  eventLocation: string
  eventDuration: string
  certificateUrl: string
  certificateId: string
  isGuestAccess?: boolean
  certificateStoragePath?: string | null
  certificateFilename?: string | null
}) => {
  const { loadCertificateEmailAttachment } = await import('@/lib/certificate-attachment')
  const attachment = await loadCertificateEmailAttachment(
    data.certificateStoragePath,
    data.certificateFilename
  )
  const mail = buildCertificateAutoGeneratedEmail({
    ...data,
    certificateUrl: data.certificateUrl || `${getAppBaseUrl()}/mycertificates`,
    hasAttachment: !!attachment,
  })
  return sendEmailWithRetry(
    data.recipientEmail,
    mail.subject,
    mail.html,
    2,
    attachment ? [attachment] : undefined
  )
}

export const sendAttendanceThankYouEmail = async (data: {
  recipientEmail: string
  recipientName: string
  eventTitle: string
  eventDate: string
  eventTime: string
}) => {
  const mail = buildAttendanceThankYouEmail(data)
  return sendEmailWithRetry(data.recipientEmail, mail.subject, mail.html)
}

export const sendConnectionRequestEmail = async (data: {
  recipientEmail: string
  recipientName: string
  requesterName: string
  connectionType: 'friend' | 'mentor'
  respondUrl: string
}) => {
  try {
    const mail = buildConnectionRequestEmail({
      ...data,
      respondUrl: data.respondUrl || `${getAppBaseUrl()}/connections`,
    })
    await sendEmailViaGraphAPI(data.recipientEmail, mail.subject, mail.html)
    return true
  } catch (error) {
    console.error('Failed to send connection request email:', error)
    return false
  }
}

export const sendConnectionAcceptedEmail = async (data: {
  recipientEmail: string
  recipientName: string
  responderName: string
  connectionType: 'friend' | 'mentor'
  dashboardUrl: string
}) => {
  try {
    const mail = buildConnectionAcceptedEmail({
      ...data,
      dashboardUrl: data.dashboardUrl || `${getAppBaseUrl()}/connections`,
    })
    await sendEmailViaGraphAPI(data.recipientEmail, mail.subject, mail.html)
    return true
  } catch (error) {
    console.error('Failed to send connection acceptance email:', error)
    return false
  }
}

export const sendConnectionReportEmail = async (data: {
  reviewerEmail: string
  reporterName: string
  targetName: string
  reason: string
  notes?: string | null
  dashboardUrl: string
}) => {
  try {
    const mail = buildConnectionReportEmail(data)
    await sendEmailWithRetry(data.reviewerEmail, mail.subject, mail.html)
    return true
  } catch (error) {
    console.error('Failed to send connection report email', error)
    return false
  }
}

export const sendConnectionReportAcknowledgementEmail = async (data: {
  recipientEmail: string
  recipientName: string
  targetName: string
  reason: string
  notes?: string | null
  dashboardUrl: string
}) => {
  try {
    const mail = buildConnectionReportAcknowledgementEmail(data)
    await sendEmailViaGraphAPI(data.recipientEmail, mail.subject, mail.html)
    return true
  } catch (error) {
    console.error('Failed to send connection report acknowledgement email:', error)
    return false
  }
}
